server:
  port: 20280
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: news
    password: news1234
#    url: jdbc:mysql://ewenlai.xin:3306/news?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/news?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2b8
  http:
    encoding:
      charset: UTF-8
  # 根据实体类自动创建数据库表
  jpa:
    hibernate:
      ddl-auto: update
  # Thymeleaf 模板热启动
  thymeleaf:
    cache: false
  # 热启动设置
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload.image}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB
# web服务器保存上传图片路径
web:
  upload:
#    image: /home/lwwen/Documents/Project/java/news/upload
    image: /home/aliyunzy/Documents/Project/java/news/upload