server:
  port: 10280
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: news
    password: news1234
    url: jdbc:mysql://localhost:3306/news?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2b8
  http:
    encoding:
      charset: UTF-8
  # 根据实体类自动创建数据库表
  jpa:
    hibernate:
      ddl-auto: update
  # Thymeleaf 模板热启动
  thymeleaf:
    cache: false
  # 热启动设置
  devtools:
    restart:
      enabled: true
  mvc:
    static-path-pattern: /static/**
img:
  location: /home/lwwen/Documents/Project/IdeaProjects/news/src/main/resources/static/upload/image